name: 'Terraform Plan & Apply'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: 'us-east-1'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tf

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        DATADOG_EXTERNAL_ID: ${{ secrets.DATADOG_EXTERNAL_ID }}

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Plan
      run: terraform plan -no-color
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        DATADOG_EXTERNAL_ID: ${{ secrets.DATADOG_EXTERNAL_ID }}
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
        DATADOG_EXTERNAL_ID: ${{ secrets.DATADOG_EXTERNAL_ID }}

    - name: Obtener Outputs de Terraform
      id: outputs
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform output -json > outputs.json
        echo "frontend_ip=$(jq -r .frontend_public_ip.value outputs.json)" >> "$GITHUB_ENV"
        echo "backend_ip=$(jq -r .backend_public_ip.value outputs.json)" >> "$GITHUB_ENV"

  deploy_agent:
    name: Despliegue del Agente Datadog
    needs: terraform
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Configurar clave SSH para EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          echo -e "Host ec2\n\tHostName ${{ secrets.EC2_INSTANCE }}\n\tUser ${{ secrets.EC2_USER }}\n\tIdentityFile ~/.ssh/ec2_key.pem\n\tStrictHostKeyChecking no" > ~/.ssh/config
      
      - name: Transferir script de instalación
        run: |
          scp ./scripts/install_datadog_agent.sh ec2:~/
      
      - name: Instalar y configurar Agente Datadog
        env:
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          ssh ec2 '
            chmod +x ~/install_datadog_agent.sh
            sudo DD_API_KEY=${{ secrets.DATADOG_API_KEY }} ~/install_datadog_agent.sh
            rm ~/install_datadog_agent.sh 